use_frameworks!

platform :ios, '10.0'

target 'MLCycleFlowLayout_Example' do
  pod 'MLCycleFlowLayout', :path => '../'

  target 'MLCycleFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
